using System.Text;

using FFXIVClientStructs.FFXIV.Component.GUI;

namespace Dalamud.Utility;

/// <summary>
/// Helpers for reading strings out of the game's fixed-size native character buffers.
/// </summary>
/// <remarks>
/// <para>
/// The <c>...String</c> properties generated by ClientStructs for fixed-size string fields decode via
/// <c>MemoryMarshal.CreateReadOnlySpanFromNullTerminated</c>, which has no upper bound: should the buffer
/// happen to hold no NUL byte, the scan simply keeps walking forwards through whatever memory follows it.
/// </para>
/// <para>
/// For buffers that get read at hazardous moments - an addon's name while that addon is being finalized,
/// for instance - that is an unbounded read over freed or unmapped memory, and the AccessViolationException
/// it eventually raises is a corrupted-state exception that no managed <c>try</c>/<c>catch</c> can contain.
/// The helpers here bound the read to the buffer that actually backs the field.
/// </para>
/// </remarks>
internal static unsafe class NativeStringUtil
{
    /// <summary>
    /// Decodes a fixed-size UTF-8 buffer into a string, stopping at the first NUL byte.
    /// </summary>
    /// <param name="buffer">The fixed-size buffer to decode.</param>
    /// <returns>
    /// The decoded string. This is identical to an ordinary NUL-terminated decode whenever the buffer does
    /// contain a NUL; when it does not, the buffer is decoded in full rather than read past its end.
    /// </returns>
    internal static string ReadFixedBuffer(ReadOnlySpan<byte> buffer)
    {
        var terminator = buffer.IndexOf((byte)0);
        return Encoding.UTF8.GetString(terminator < 0 ? buffer : buffer[..terminator]);
    }

    /// <summary>
    /// Gets the name of an addon, bounded to the 32-byte buffer that backs <c>AtkUnitBase.Name</c>.
    /// </summary>
    /// <param name="addon">The addon to read the name of. May be <c>null</c>.</param>
    /// <returns>
    /// The addon's name, or <see cref="string.Empty"/> when <paramref name="addon"/> is <c>null</c>.
    /// </returns>
    internal static string GetAddonName(AtkUnitBase* addon)
        => addon is null ? string.Empty : ReadFixedBuffer(addon->Name);
}
